---
title: "Final Report of transportation service in the holy month of Ramadan"
author: "Ahmad Mutaher"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE, warning=FALSE}

library(here)
library(tidyverse)
library(knitr)
library(dplyr)
library(plotly)

Buses_Data <- read_csv(here("./BusesFile.csv"))
glimpse(Buses_Data)

# Bus Table for the whole month
Tbl_Bus <- tibble::tribble(
    ~Day_Name, ~Date_number, ~Ajyad1, ~Ajyad2, ~BabAli, ~AmerStation, ~King.Abdullah, ~Al.Kabaa.Mountian, ~Jarwal, ~Baksh,
     "Friday",           29,     261,      42,     194,          368,            120,                133,     155,     65,
   "Saturday",            1,     360,      93,     232,          401,            120,                168,     415,     90,
     "Sunday",            2,     315,      70,     254,          422,            120,                173,     160,    112,
     "Monday",            3,     352,      90,     211,          429,            120,                174,     255,    112,
    "Tuesday",            4,     367,     114,     245,          433,            120,                164,     263,    112,
  "Wednesday",            5,     367,     130,     215,          433,            120,                176,     292,    114,
   "Thursday",            6,     376,     142,     262,          441,            129,                177,     277,    114,
     "Friday",            7,     395,     150,     264,          443,            132,                182,     328,    114,
   "Saturday",            8,     396,     155,     250,          456,            140,                180,     397,    124,
     "Sunday",            9,     388,     158,     258,          458,            137,                176,     339,    124,
     "Monday",           10,     368,     157,     262,          458,            130,                173,     306,    125,
    "Tuesday",           11,     375,     165,     260,          466,            135,                178,     333,    128,
  "Wednesday",           12,     367,     159,     259,          468,            130,                176,     327,    130,
   "Thursday",           13,     397,     161,     257,          470,            131,                184,     306,    132,
     "Friday",           14,     420,     169,     263,          473,            130,                179,     301,    133,
   "Saturday",           15,     420,     159,     251,          480,            130,                184,     308,    133,
     "Sunday",           16,     420,     170,     248,          481,            138,                181,     312,    134,
     "Monday",           17,     420,     174,     236,          482,            139,                181,     309,    134,
    "Tuesday",           18,     460,     173,     262,          487,            141,                179,     307,    143,
  "Wednesday",           19,     460,     170,     250,          493,            140,                184,     305,    143,
   "Thursday",           20,     460,     167,     277,          495,            140,                184,     313,    143,
     "Friday",           21,     460,     188,     273,          494,            142,                181,     299,    143,
   "Saturday",           22,     460,     189,     282,          493,            140,                178,     306,    143,
     "Sunday",           23,     460,     172,     280,          514,            150,                177,     290,    143,
     "Monday",           24,     460,     168,     281,          511,            150,                179,     299,    143,
    "Tuesday",           25,     460,     163,     276,          516,            150,                181,     307,    143,
  "Wednesday",           26,     460,     172,     271,          513,            150,                186,     282,    143,
   "Thursday",           27,     460,     158,     265,          509,            150,                189,     320,    143,
     "Friday",           28,     460,     176,     258,          507,            150,                181,     315,    143,
   "Saturday",           29,     460,     180,     282,          488,            150,                187,     323,    143,
     "Sunday",            1,       0,       0,     180,          464,              0,                 73,     185,    143
  )

require(knitr)
kable(Tbl_Bus, digits = 3, row.names = FALSE, align = "c",
              caption = "Statistics of Buses for all days")

TotalBusForEachDay <- Buses_Data %>%
                    select(Day_Name:Baksh)
 
TotalBusForEachDay <- TotalBusForEachDay %>% mutate("Sum_Of_Day" = rowSums((TotalBusForEachDay[,3:10]), na.rm = TRUE))

fig1 <- plot_ly(TotalBusForEachDay, x = ~Date_number, y = ~Sum_Of_Day,
               marker = list(size = 10,
                             color = 'rgba(200, 110, 160, .9)',
                             line = list(color = 'rgba(152, 0, 0, .8)',
                                         width = 2)))
fig1 <- fig1 %>% layout(title = 'Days distribution',
         yaxis = list(zeroline = FALSE),
         xaxis = list(zeroline = FALSE))
fig1

fig2 <- plot_ly(TotalBusForEachDay, x = ~Day_Name, y = ~Sum_Of_Day,
               marker = list(size = 10,
                             color = 'rgba(153, 170, 200, .9)',
                             line = list(color = 'rgba(230, 255, 255, .8)',
                                         width = 2)))
fig2 <- fig2 %>% layout(title = 'The days when the largest number of buses were pumped',
         yaxis = list(zeroline = FALSE),
         xaxis = list(zeroline = FALSE))
fig2

sumOfBuseForAllStations <- Buses_Data %>%
                           select(Ajyad1:Baksh) %>%
                           summarise_all(sum)

kable(sumOfBuseForAllStations, digits = 3, row.names = FALSE, align = "c",
              caption = " Sum of Buses for each station")


sumOfBuseForJuma <- Buses_Data %>%
                    select(Day_Name:Baksh)%>%
                    filter(Day_Name == "Friday")      
                           
kable(sumOfBuseForJuma, digits = 3, row.names = FALSE, align = "c",
              caption = " Bus count For all Jumaa Days")



```